comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
ignore:
  - "installer/pkg/obj/kubeobj"
  - "installer/pkg/templategenerator"
  - "installer/cmd"
  - "agent/pkg/main.go"
  - "installer/pkg/install/cmd.go"
  - "agent/pkg/infra/git/provider/api/gitlab_api" # it is not possible to test