comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
ignore:
  - "installer/pkg/obj/kubeobj"
  - "installer/pkg/prompt"
  - "installer/pkg/templategenerator"
  - "installer/pkg/logger/log.go"
  - "installer/cmd"
  - "installer/main.go"
  - "agent/pkg/infra/newrelic/newrelic.go"
  - "agent/pkg/infra/git/provider/api/github_api.go"
  - "agent/pkg/infra/logger/logger.go"

  - "agent/pkg/main.go"
  - "agent/pkg/infra/git/provider/api/gitlab_api" # it is not possible to test