apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cf-argocd-agent{{ .Codefresh.Suffix }}
  name: cf-argocd-agent{{ .Codefresh.Suffix }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs:
      - get
      - list
      - watch
