apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cf-argocd-agent{{ .Codefresh.Suffix }}
  name: cf-argocd-agent{{ .Codefresh.Suffix }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-argocd-agent{{ .Codefresh.Suffix }}
subjects:
  - kind: ServiceAccount
    name: cf-argocd-agent{{ .Codefresh.Suffix }}
    namespace: {{ .Namespace }}