apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-argocd-agent
  name: cf-argocd-agent
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: cf-argocd-agent
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cf-argocd-agent
    spec:
      serviceAccountName: cf-argocd-agent
      containers:
      - env:
        {{- if .Host.HttpProxy }}
        - name: HTTP_PROXY
          value: {{ .Host.HttpProxy }}
        - name: http_proxy
          value: {{ .Host.HttpProxy }}
        {{- end }}
        {{- if .Host.HttpsProxy }}
        - name: HTTPS_PROXY
          value: {{ .Host.HttpsProxy }}
        - name: https_proxy
          value: {{ .Host.HttpsProxy }}
        {{- end }}
        - name: AGENT_VERSION
          value: "{{ .Agent.Version }}"
        - name: ARGO_HOST
          value: {{ .Argo.Host }}
        - name: ARGO_USERNAME
          value: {{ .Argo.Username }}
        - name: ARGO_PASSWORD
          value: {{ .Argo.Password }}
        - name: ARGO_TOKEN
          valueFrom:
            secretKeyRef:
              name: cf-argocd-agent
              key: argo.token
        - name: CODEFRESH_HOST
          value: {{ .Codefresh.Host }}
        - name: CODEFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: cf-argocd-agent
              key: codefresh.token
        - name: IN_CLUSTER
          value: "{{ .Kube.InCluster }}"
        - name: MASTERURL
          value: "{{ .Kube.MasterUrl }}"
        - name: BEARERTOKEN
          valueFrom:
            secretKeyRef:
              name: cf-argocd-agent
              key: kube.bearertoken
        - name: SYNC_MODE
          value: "{{ .Codefresh.SyncMode }}"
        - name: APPLICATIONS_FOR_SYNC
          value: "{{ .Codefresh.ApplicationsForSync }}"
        - name: CODEFRESH_INTEGRATION
          value: {{ .Codefresh.Integration }}
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cf-argocd-agent
              key: git.password
        image: codefresh/argocd-agent:stable
        imagePullPolicy: Always
        name: cf-argocd-agent
      restartPolicy: Always